INSERT INTO HEROE(ID, NOMBRE)
VALUES (3466, 'Batman');
INSERT INTO HEROE(ID, NOMBRE)
VALUES (5986, 'Superman');
INSERT INTO HEROE(ID, NOMBRE)
VALUES (9697, 'Wolverine');
INSERT INTO HEROE(ID, NOMBRE)
VALUES (9398, 'Spiderman');