INSERT INTO HEROE(ID, NOMBRE)
VALUES (3466, 'Batman');
INSERT INTO HEROE(ID, NOMBRE)
VALUES (5986, 'Superman');
INSERT INTO HEROE(ID, NOMBRE)
VALUES (9697, 'Wolverine');
INSERT INTO HEROE(ID, NOMBRE)
VALUES (9398, 'Spiderman');
INSERT INTO HEROE(ID, NOMBRE)
VALUES (5987, 'Manolito el fuerte”,');

INSERT INTO ROLE (NAME)
VALUES ('ROLE_ADMIN');
INSERT INTO ROLE (NAME)
VALUES ('ROLE_USER');
INSERT INTO ROLE (NAME)
VALUES ('ROLE_MOD');